### PR TITLE
New features

### PR DESCRIPTION
**Pull request by RobertoSchneiders**
From what I understand, the requests were being made ​​every 5 minutes and not every 5 seconds ([Check this](http://cronchecker.net/check?utf8=%E2%9C%93&statement=*%2F5+*+*+*+*+*&button=)). I changed to 1 minute.

I changed to use the heroku environment variables. Thus it is not necessary to change the code to use the bot. 

Added support for multiple languages​​, the default is English.

### CODE REVIEW

**Comment by sbehrends** [comment]
Nice job.
Regarding the cron, if you take a look at the console log the request is done every 5 seconds.

``` javascript
2014-06-13T20:05:20.290851+00:00: Looking for match update
2014-06-13T20:05:25.294529+00:00: Looking for match update
2014-06-13T20:05:30.297446+00:00: Looking for match update
```

**Comment by RobertoSchneiders** [comment]
Thank you. 

Interesting. I will keep the way it was then.

**Comment by RobertoSchneiders** [comment]
Done. 

The indentation looks a bit confused, has tabs in some places and spaces in others. I did not changed to not disrupt the diff.

**Comment by RobertoGonzalez** [comment]
@RobertoSchneiders The cron package that's being used here is slightly different than the *nix one. On linux the smallest unit is minutes and in this package is seconds, which caused the seconds/minutes confusion.

**Comment by RobertoSchneiders** [comment]
Thanks for clarifying @RobertoGonzalez. I do not have much experience with Javascript, did not know that.

**Pull request merged**
